name: 'Angular Build'
description: 'Builds an Angular App'
inputs:
  environment:
    required: true
    type: string
    default: 'dev'
  project-name:
    required: true
    type: string
  project-type:
    required: true
    type: string
  node-version:
    type: string
    default: '14.x'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
    - run: npm install
      shell: bash
    - run: npm install -g @angular/cli > /dev/null
      shell: bash
    - name: Build ${{ inputs.project-name }}
      run: ng build --output-path=dist
      shell: bash
    - name: Upload Artifact (Output)
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.environment }}-artifact
        path: dist
